services:
  ebote:
    build: ./
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - 8004:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    depends_on:
      ebote-db:
        condition: service_healthy

  ebote-db:
    image: postgres:17.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ebote_user
      POSTGRES_PASSWORD: ebote_pass
      POSTGRES_DB: ebote
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5