services:
  ebote:
    build: ./
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "8004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
  
  ebote-db:
    image: postgres:17-alpine
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ebote_user
      - POSTGRES_PASSWORD=ebote_pass