// This file is auto-generated by @hey-api/openapi-ts

export const AccountModelSchema = {
    required: ['login', 'passwordHash'],
    type: 'object',
    properties: {
        login: {
            type: 'string',
            nullable: true
        },
        passwordHash: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;