// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { PostAccountSignUpData, PostAccountSignUpError, PostAccountSignUpResponse, PostAccountLoginData, PostAccountLoginError, PostAccountLoginResponse, GetAccountLogoutError, GetAccountLogoutResponse, GetAccountCheckAuthError, GetAccountCheckAuthResponse } from './types.gen';

export const client = createClient(createConfig());

export const postAccountSignUp = <ThrowOnError extends boolean = false>(options?: Options<PostAccountSignUpData, ThrowOnError>) => { return (options?.client ?? client).post<PostAccountSignUpResponse, PostAccountSignUpError, ThrowOnError>({
    ...options,
    url: '/Account/SignUp'
}); };

export const postAccountLogin = <ThrowOnError extends boolean = false>(options?: Options<PostAccountLoginData, ThrowOnError>) => { return (options?.client ?? client).post<PostAccountLoginResponse, PostAccountLoginError, ThrowOnError>({
    ...options,
    url: '/Account/Login'
}); };

export const getAccountLogout = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetAccountLogoutResponse, GetAccountLogoutError, ThrowOnError>({
    ...options,
    url: '/Account/Logout'
}); };

export const getAccountCheckAuth = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetAccountCheckAuthResponse, GetAccountCheckAuthError, ThrowOnError>({
    ...options,
    url: '/Account/CheckAuth'
}); };